version: '3.8'

services:
  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/confluence
      - ATL_JDBC_USER=confluence_user
      - ATL_JDBC_PASSWORD=confluence_pass
      - ATL_DB_TYPE=postgresql
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: confluence_db
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence_user
      POSTGRES_PASSWORD: confluence_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  confluence_data:
  postgres_data: